### ISSUE TITLE
Support for GPU

### ISSUE THREAD

**Issue by Euregan** [stsdc/monitor#221]
Hello,

Is there any support for GPU stats? Can I do anything to help on this topic?

**Comment by stsdc** [comment]
Hello! Indeed, it would be cool to have GPU stats. The main problem is that not all GPUs are providing access to this stats. As I know newer  Radeons do create files with such info like temp., freq., vmem. But I didn't really dive into this.

Research in this topic would be apreciated, but PRs would be even more! Since I do not have a lot of spare time for this project recently, it is easier for me to review and maintain for now :disappointed:

**Comment by davidak** [comment]
MangoHud shows stats for GPU. Maybe you can get some information there and maybe reuse code.

https://github.com/flightlessmango/MangoHud

**Comment by stsdc** [comment]
@Euregan added support for amdgpu
![image](https://user-images.githubusercontent.com/6031763/141321792-cad3d502-741d-49c4-bd20-8a0f5c571d34.png)

**Comment by camellan** [comment]
Hi. There is a libXNVCtrl API for Nvidia graphics cards. My successful research on this subject is here: 
[https://github.com/camellan/nvstat](url), but I don't know how to relate it to vala.

**Comment by stsdc** [comment]
@camellan thanks. Probably a custom [VAPI bindings has to be written](https://wiki.gnome.org/action/show//Projects/Vala/ManualBindings?action=show&redirect=Projects%2FVala%2FLegacyBindings). I tried to find one, thought maybe someone already wrote that somewhere on Github, but didn't find. If there will be a VAPI I'll use that.

**Comment by camellan** [comment]
@stsdc, Unfortunately, I am not a very good programmer. I'm not a programmer at all ). But I'll try. Maybe I can figure it out.

**Comment by camellan** [comment]
@stsdc, I was able to do it ) [https://github.com/camellan/nvstat](url)

**Comment by stsdc** [comment]
@camellan nice, I'm waiting for a PR :)
I don't have a nvidia gpu to test.

**Comment by camellan** [comment]
> @camellan nice, I'm waiting for a PR :)
> I don't have a nvidia gpu to test.

It won't be easy.  I am a bad programmer...

**Comment by stsdc** [comment]
fixed in #276
