### ISSUE TITLE
Error: assertion 'desktop_file != NULL' failed

### ISSUE THREAD

**Issue by stsdc** [stsdc/monitor#53]
[DEBUG 15:45:47.242027] AppManager.vala:119: Window type: 0, Is transient: 0
    [FATAL 15:45:47.255918] monitor_app_manager_has_desktop_file: assertion 'desktop_file != NULL' failed`

**Comment by h4ndshake** [comment]
You're probably dealing with an special "app", which has a window but not a desktop file (not sure if it **IS** the case (since i've never dove deep on elementary (or vala) internals), but your problem might be gala (wingpanel and the dock might also be the culprit).

Again: I've never dove deep on elementary internals, nor have experience with that type of software, but that's the only thing I can think of.

You might as well add a debug line like:
```c
debug ("App info: %d, %s, %s", pids, name, desktop_file);
```

See: https://github.com/stsdc/monitor/blob/master/src/Managers/AppManager.vala#L108

**Comment by ie900** [comment]
Or you can use `gdb` or similar tools like all normal people.

Do not forget that Vala is translated into normal C code, so the application can be easily analyzed using the usual Unix and Linux system programmer tools.

**Comment by ie900** [comment]
https://lazka.github.io/pgi-docs/Bamf-3/classes/Application.html#Bamf.Application.get_desktop_file

> Used to fetch the path to the .desktop file associated with the passed application. If none exists, the result is None.

https://git.launchpad.net/bamf/tree/src/bamf-application.c#n159

> const char *

That is, if there is no file, `null` is returned.
The return value is a pointer to a string.
But in your `has_desktop_file`, just `string` is specified - in the Vala language this implies the existence of a string.
Thus, when passed with the argument `null`, the program is expected to fall. If `null` is valid, indicate this explicitly.

Alas, Vala is not Java - you do not have a virtual machine, so you must remember what you are actually working with.

**Comment by ie900** [comment]
**Change**
```vala
private bool has_desktop_file (string desktop_file) {
```
**to**
```vala
private bool has_desktop_file (string? desktop_file) {
```
**fixes this issue.**
